# Tên và điều kiện kích hoạt
name: Deploy Backend

on:
  push:
    branches: ["main"] # Chỉ chạy khi push code vào nhánh main.
    paths:
      # Chỉ chạy khi có thay đổi trong thư mục
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
  workflow_dispatch: # Cái này tạo ra một nút bấm "Run" trên web để bạn tự kích hoạt bằng tay

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # name: label
        uses: actions/checkout@v4 # actions/checkout@v4 là tool viết sẵn
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Unit Tests
        run: mvn test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code # Giống việc clone code từ repo về máy ubuntu
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3 # docker/login-action@v3 là tool viết sẵn
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # <--- QUAN TRỌNG: Dấu chấm (.) nghĩa là "Tìm Dockerfile ngay tại chỗ tui đang đứng"
          push: true # Build xong thì đẩy lên kho luôn
          tags: |    # Dán nhãn cho kiện hàng
            ${{ secrets.ACR_SERVER }}/backend-app:latest
            ${{ secrets.ACR_SERVER }}/backend-app:${{ github.sha }}